POST http://localhost:4500/login
content-type: application/json

{
  "name": "pepe",
  "passwd": "12345"
}

####

POST http://localhost:4500/login
content-type: application/json

{
  "name": "Pepe",
  "passwd": "123"
}

####

POST http://localhost:4500/login
content-type: application/json

{
  "name": "Juanito",
  "passwd": "123"
}

####

POST http://localhost:4500/login
content-type: application/json

{
  "name": "Juanito",
  "passwd": ""
}
